// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1PZ8Ve-9ntSyav3BatwMdz9D0nGGpgjY',
    appId: '1:212352692260:web:9127e6bd0d320689d028b1',
    messagingSenderId: '212352692260',
    projectId: 'food-delivery-flutter-ap-9d259',
    authDomain: 'food-delivery-flutter-ap-9d259.firebaseapp.com',
    storageBucket: 'food-delivery-flutter-ap-9d259.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTn5ncKAAOY54ewBblHvnbouNh1Th1dkw',
    appId: '1:212352692260:android:20a458fc5fcb4876d028b1',
    messagingSenderId: '212352692260',
    projectId: 'food-delivery-flutter-ap-9d259',
    storageBucket: 'food-delivery-flutter-ap-9d259.appspot.com',
  );
}
